### ISSUE TITLE
Need method to get all my test-ids

### ISSUE THREAD

**Issue by jmythms** [NatLabRockies/boptest-service#1]

**Comment by kbenne** [comment]
+1 seems like a top priority to me.

**Comment by kbenne** [comment]
possible api GET `/tests` with API Key

**Comment by jmythms** [comment]
Notes:

possible examples:
users:jermy:tests:"9028197e-1d18-4a58-a6ba-96660c50fb7a" = {status:"Running", testcaseid:"testcase_1"}


users:jmythms:tests = 
[
"9028197e-1d18-4a58-a6ba-96660c50fb7a", 
"9028197e-1d18-4a58-a6ba-96660c50fb7a",
]


ps: Don't use redis keys.
@jmythms will get performance implications of redis key length.

**Comment by jmythms** [comment]
@jmythms Can we use client IP for anonymous users? Check for best practices.
