### ISSUE TITLE
Need a method to kill all my running tests

### ISSUE THREAD

**Issue by jmythms** [NatLabRockies/boptest-service#2]

**Comment by kbenne** [comment]
We have the `stop` api. Would this be effectively `stop all`? Maybe that would be implemented by calling stop with no test id. 

I feel like the other part of this is that sometimes we might want to really forcefully halt the simulation. Like when PyFMI hangs up. Maybe the answer is to make stop more powerful such that it can interrupt PyFMI? Not sure how we would implement that, but it would almost surely involve threading. 

I think in the case of hung jobs a watchdog is part of the answer.
