### ISSUE TITLE
Add API to download the test results archive

### ISSUE THREAD

**Issue by dhblum** [NatLabRockies/boptest-service#28]
This is a transfer from https://github.com/ibpsa/project1-boptest/issues/462.

**Comment by dhblum** [comment]
@kbenne Awesome!  Is there a public API or method for this?

**Comment by kbenne** [comment]
> @kbenne Awesome! Is there a public API or method for this?

Yes, but we need to deploy some changes on the cluster to make this all work. I'll document how to perform downloads once  it is live on the cluster and also alert you when it is ready.
